#!/usr/bin/env ruby
require 'rubygems'
require 'json'
require 'yaml'
YAML::ENGINE.yamler = 'syck'
DIR_ROOT = File.expand_path(File.dirname(__FILE__))
puts DIR_ROOT
YAML_ROOT = File.join(DIR_ROOT, '../config/locales')
puts YAML_ROOT
JS_ROOT = File.join(DIR_ROOT, '../app/assets/javascripts', 'locales')
puts JS_ROOT
# locale javascript namespace
JS_NAMESPACE = 'i18n = '

Dir[File.join(YAML_ROOT, 'salor.*.yml')].sort.each { |locale| 
  locale_yml = YAML::load(IO.read(locale))
  puts 'Filename: ' + locale
  File.open(
    File.join(JS_ROOT, File.basename(locale, '.*') + '.js'), 'w') {|f| 
      tmp = locale_yml[File.basename(locale, '.*').split('.')[1]]
      final = {}
      tmp.each do |k,v|
        final[k] = v if not [:time,:date].include? k.to_sym
      end
    f.write(JS_NAMESPACE + final.to_json)
  }
}
