#!/bin/bash
# postinst script for salor-retail
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

. /usr/share/debconf/confmodule

installation_root=/usr/share/salor-retail
app_root=${installation_root}/source

echo ""
echo "POSTINST called with $@"
echo "===================================="

echo "  Remove and purge old-instances"
# the following code to clear old instances must be here in postinst because of the following reasons:
#   1) dpkg-reconfigure DOES call prerm but does NOT call postrm, therefore the code cannot go into postrm.
#   2) prerm is called BEFORE the config script. Since old-instances is set up only in the config script, the code cannot be in prerm.
#   3) Therefore, the only place is here in postrm.

db_get salor-retail/old-instances || true
gOldInstances="${RET}"
for lInstance in $gOldInstances; do
  echo "    Instance $lInstance"
  db_get salor-retail/instances/$lInstance/dbconfig-install || true
  if [ "$RET" = "true" ]; then
    ( . /usr/share/dbconfig-common/dpkg/prerm ; dbc_go salor-retail/instances/$lInstance remove )
    ( . /usr/share/dbconfig-common/dpkg/postrm ; dbc_go salor-retail/instances/$lInstance purge )
  fi
  
  if which ucf >/dev/null 2>&1; then
    ucf --purge /etc/salor-retail/$lInstance/database.yml
    ucf --purge /etc/salor-retail/$lInstance/config.yml
    ucf --purge /etc/salor-retail/$lInstance/codepages.yml
    ucf --purge /etc/salor-retail/$lInstance/Gemfile
    ucf --purge /etc/salor-retail/$lInstance/Gemfile.lock
    ucf --purge /etc/salor-retail/$lInstance/sr-$lInstance-apache-http
    ucf --purge /etc/salor-retail/$lInstance/sr-$lInstance-apache-https
    ucf --purge /etc/salor-retail/$lInstance/sr-$lInstance-nginx-http
    ucf --purge /etc/salor-retail/$lInstance/sr-$lInstance-nginx-https
  fi
  
  rm -rf /etc/salor-retail/$lInstance
  rm -rf /etc/salor-retail/$lInstance/sr-$lInstance-apache2-http
  rm -rf /etc/salor-retail/$lInstance/sr-$lInstance-apache2-https
  rm -rf /etc/salor-retail/$lInstance/sr-$lInstance-nginx-http
  rm -rf /etc/salor-retail/$lInstance/sr-$lInstance-nginx-https
  rm -rf /usr/share/salor-retail/$lInstance
  rm -rf /var/log/salor-retail/$lInstance
  rm -rf /var/cache/salor-retail/$lInstance
  rm -rf /var/lib/salor-retail/$lInstance
  rm -rf /var/tmp/salor-retail/$lInstance
done
db_set salor-retail/old-instances ""

case "$1" in
  configure)
    echo "  postinst: Adding pcspkr to /etc/modules if not yet there..."
    result=`cat /etc/modules | grep 'pcspkr' | wc -l`
    if [ "$result" = "0" ]; then
      echo "pcspkr" >> /etc/modules;
    fi
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
      echo "postinst called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac


db_get salor-retail/current-instances || true
gInstances="${RET}"
for lInstance in $gInstances; do
  case "$1" in
    configure)
    
      echo ""
      echo "               $lInstance"
      echo "  -----------------------------------"
      
      rails_etc=/etc/salor-retail/$lInstance
      rails_log=/var/log/salor-retail/$lInstance
      rails_cache=/var/cache/salor-retail/$lInstance
      rails_var=/var/lib/salor-retail/$lInstance
      rails_tmp=/var/tmp/salor-retail/$lInstance
      
      echo "  postinst: creating directories"
      mkdir -p $rails_etc
      mkdir -p $rails_log
      mkdir -p $rails_cache
      mkdir -p $rails_var/public/uploads/$lInstance
      mkdir -p $rails_tmp
      
      use_dbconfig=false
      
      db_get salor-retail/instances/$lInstance/dbconfig-install || true
      if [ "$RET" = "true" ]; then
        echo "  postinst: dbconfig-install is $RET. Setting use_dbconfig to TRUE"
        use_dbconfig=true
        db_get salor-retail/instances/$lInstance/dbconfig-reinstall || true
        if [ "$RET" = "false" ]; then
          echo "  postinst: dbconfig-reinstall is $RET"
          db_fget salor-retail/instances/$lInstance/dbconfig-reinstall seen || true
          if [ "$RET" = "true" ]; then
            echo "  postinst: dbconfig-reinstall seen is $RET. Setting use_dbconfig to FALSE."
            use_dbconfig=false
          fi
        fi
      fi
      
      if [ ! -f /etc/salor-retail/$lInstance/database.yml.lock ]; then
        database_config_yml_template="$app_root/config/database.yml.template"
        database_config_yml=$rails_etc/database.yml.new
        if [ $use_dbconfig = true ]; then
          echo "  postinst: generating database.yml configuration file"
          dbc_generate_include=template:$database_config_yml
          dbc_generate_include_args="-o template_infile=$database_config_yml_template"
          dbc_mysql_createdb_encoding="UTF8"
          ucf --purge $database_config_yml
          ( . /usr/share/dbconfig-common/dpkg/postinst ; dbc_go salor-retail/instances/$lInstance $@ ) # dbc_go is automatically registering database.yml.new as config file. however, since this is only our temporary file, we have to purge it. The real, permanent file is called database.yml
          ucf --purge $database_config_yml
          ucf --debconf-ok $database_config_yml /etc/salor-retail/$lInstance/database.yml
          chmod 660 /etc/salor-retail/$lInstance/database.yml
          rm -rf $database_config_yml
        fi
      fi

      echo "  postinst: creating symlinks"
      ln -sfn $app_root /usr/share/salor-retail/${lInstance}
      rm -rf $app_root/public/uploads/${lInstance} # remove symlink, then create a new one
      mkdir -p $rails_var/public/uploads/${lInstance}
      ln -sfn $rails_var/public/uploads/${lInstance} $app_root/public/uploads/${lInstance}
      rm -rf $app_root/tmp # remove real directory in case it was created by Rails
      ln -sfn /var/tmp/salor-retail $app_root/tmp
 
      if [ $use_dbconfig = true ]; then
        # this file prevents dbconfig-common to ask for reconfiguration of the instance during dpkg-reconfigure. see config script.
        touch $rails_etc/database.yml.lock
      fi
      
      echo "  postinst: Deleting the asset cache"
      rm -rf /var/tmp/salor-retail/cache
      
      if [ -e $app_root/db/schema.rb ]; then
        echo "  postinst: Copying schema.rb to instance directory."
        cp $app_root/db/schema.rb $rails_var
      fi
      if [ -e $app_root/config/config.yml ]; then
        echo "  postinst: Installing config.yml as config file ..."
        ucf --debconf-ok $app_root/config/config.yml $rails_etc/config.yml
        chmod 660 $rails_etc/config.yml
      fi
      if [ -e $app_root/config/codepages.yml ]; then
        echo "  postinst: Installing codepages.yml as config file ..."
        ucf --debconf-ok $app_root/config/codepages.yml $rails_etc/codepages.yml
        chmod 660 $rails_etc/codepages.yml
      fi
      
      echo "  postinst: Installing Gemfile as configuration file ..."
      gemfile_source=$app_root/Gemfile
      gemfile_target=$rails_etc/Gemfile
      ucf --debconf-ok $gemfile_source $gemfile_target

      echo "  postinst: Installing Gemfile.lock as configuration file ..."
      gemfile_lock_source=$app_root/Gemfile.lock
      gemfile_lock_target=$rails_etc/Gemfile.lock
      ucf --debconf-ok $gemfile_lock_source $gemfile_lock_target
      
      hasPack=$(dpkg -l | grep salor-virtual | wc -l)
      if [ "$hasPack" = "0" ]; then
        echo "  postinst: All required gems are available as Debian packages. Nothing to be done."
      else
        echo "  postinst: Some of the required gems are not available as Debian packages. We have to run bundle install to download gems from rubygems.org."
        salor-installgems r ${lInstance}
      fi
      
      if [ -e $rails_etc/database.yml ]; then
        echo "  postinst: this instance has a configured database."
        cd $app_root        
        echo "  postinst: migrating the database. this may take a while."
        rake1.9.1 --trace db:migrate RAILS_ENV=production SR_DEBIAN_SITEID="${lInstance}" BUNDLE_GEMFILE="${gemfile_target}" #> /dev/null
        echo "  postinst: running db:seed ..."
        rake1.9.1 --trace db:seed SEED_MODE=minimal RAILS_ENV=production SR_DEBIAN_SITEID="${lInstance}" BUNDLE_GEMFILE="${gemfile_target}" #> /dev/null
      else
        echo "  postinst: $rails_etc/database.yml does not exist. Instance \"${lInstance}\" database must be configured manually."
      fi
      
      for protocol in http https; do
        echo "  postinst: creating apache2 and nginx site configuration file for $protocol..."
        apache_site_maintainer_config=/etc/salor-retail/$lInstance/sr-$lInstance-apache2-$protocol
        nginx_site_maintainer_config=/etc/salor-retail/$lInstance/sr-$lInstance-nginx-$protocol
        cp $app_root/config/apache-site-$protocol.template $apache_site_maintainer_config.maintainer
        cp $app_root/config/nginx-site-$protocol.template $nginx_site_maintainer_config.maintainer
        sed -i "s/INSTANCE_ID/${lInstance}/g" $apache_site_maintainer_config.maintainer
        sed -i "s/INSTANCE_ID/${lInstance}/g" $nginx_site_maintainer_config.maintainer
        ucf --debconf-ok $apache_site_maintainer_config.maintainer $apache_site_maintainer_config
        ucf --debconf-ok $nginx_site_maintainer_config.maintainer $nginx_site_maintainer_config
        rm -rf $apache_site_maintainer_config.maintainer
        rm -rf $nginx_site_maintainer_config.maintainer
      done
     
      echo "  postinst: Adding salor-retail to /etc/hosts if not yet there..."
      result=`cat /etc/hosts | grep "${lInstance}.sr.localhost" | wc -l`
      if [ "$result" = "0" ]; then
        echo "::1 ${lInstance}.sr.localhost" >> /etc/hosts;
        echo "127.0.0.1 ${lInstance}.sr.localhost" >> /etc/hosts;
      fi
      ;;

      abort-upgrade|abort-remove|abort-deconfigure)
      ;;

      *)
          echo "postinst called with unknown argument \`$1'" >&2
          exit 1
      ;;
  esac
done    
    
    
db_get salor-retail/user || true
app_user=$RET
echo "  postinst: changing ownership for user $app_user"
chown -R $app_user:$app_user $installation_root
chown -R $app_user:$app_user /etc/salor-retail
chown -R $app_user:$app_user /var/cache/salor-retail
chown -R $app_user:$app_user /var/lib/salor-retail
chown -R $app_user:$app_user /var/tmp/salor-retail
chown -R $app_user:$app_user /var/log/salor-retail

echo "  postinst: changing permissions for user $app_user"
chmod -R 700 $installation_root
chmod -R 700 /etc/salor-retail
chmod -R 700 /var/cache/salor-retail
chmod -R 700 /var/lib/salor-retail
chmod -R 700 /var/tmp/salor-retail
chmod -R 700 /var/log/salor-retail

# dh_installdeb will replace this special comment with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
