Document: salor-retail
Title: Debian salor-retail Manual
Author: <insert document author here>
Abstract: This manual describes what salor-retail is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/salor-retail/salor-retail.sgml.gz

Format: postscript
Files: /usr/share/doc/salor-retail/salor-retail.ps.gz

Format: text
Files: /usr/share/doc/salor-retail/salor-retail.text.gz

Format: HTML
Index: /usr/share/doc/salor-retail/html/index.html
Files: /usr/share/doc/salor-retail/html/*.html
