source 'https://rubygems.org'
# The following are already part of Debian Jessie/sid and do not cause a dependency to the online API of rubygems.org

gem 'rails', '3.2.6'
gem 'rake', '0.9.2.2'
gem 'rack','1.4.1'
gem 'mysql2'
gem 'kramdown'
gem 'jquery-rails','2.0.2'
gem 'haml','4.0.0'
gem 'sass'
gem 'sass-rails'
gem 'coffee-rails'
gem 'rmagick'
gem 'uglifier', '1.3.0'
gem 'nokogiri'
gem 'mechanize'
gem 'json'
gem 'serialport'
gem 'money', '5.1.1'
gem 'money-rails', '0.8.1'

# The following are not yet part of Debian Jessie/sid but of the Red E repository and do NOT cause a dependency to the online API of rubygems.org

gem 'escper', '1.2.1'

# The following are not yet part of Debian Jessie/sid and cause a dependency to the online API of rubygems.org

gem 'kaminari', '0.14.1'



# The following are only required in development

gem 'i18n-js'

group :test, :development do
  gem 'debugger'
end
